export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  TRANSPORT_MANAGER: "TRANSPORT_MANAGER",
  DISPATCHER: "DISPATCHER",
  MAINTENANCE_MANAGER: "MAINTENANCE_MANAGER",
  SUPPORT_STAFF: "SUPPORT_STAFF",
  DRIVER: "DRIVER",
  CONDUCTOR: "CONDUCTOR",
  PASSENGER: "PASSENGER",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ADMIN_ROLES: Role[] = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.TRANSPORT_MANAGER,
  ROLES.DISPATCHER,
  ROLES.MAINTENANCE_MANAGER,
  ROLES.SUPPORT_STAFF,
];
